service1:
  circuit-breaker:
    threshold: 50
    wait:
      time: 9999
    closed:
      state:
        buffer: 4
  time-limiter:
    timeout: 5

service2:
  circuit-breaker:
    threshold: 60
    wait:
      time: 4000
    closed:
      state:
        buffer: 4
  time-limiter:
    timeout: 9

test: tessssst
hahahaha: RISADA